# Generated by Django 4.1.5 on 2023-02-12 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appname", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PhoneNumber",
        ),
    ]
