# Generated by Django 4.1.5 on 2023-02-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0005_rename_contact_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
