# Generated by Django 4.1.5 on 2023-02-14 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0007_feedback_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
