# Generated by Django 4.1.5 on 2023-02-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0009_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
