# Generated by Django 4.1.5 on 2023-03-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0013_enquiry_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='name',
            field=models.CharField(default='', max_length=15),
        ),
    ]
