# Generated by Django 4.1.5 on 2023-03-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0014_otp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='Address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
