# Generated by Django 4.1.5 on 2023-03-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0016_rename_otp_otp_otp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
