# Generated by Django 4.1.5 on 2023-03-29 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0017_otp_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='Address',
            new_name='address',
        ),
    ]
