# Generated by Django 4.1.5 on 2023-04-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0018_rename_address_otp_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='otp',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='otp',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_id',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
