# Generated by Django 4.1.5 on 2023-04-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0019_remove_otp_created_at_alter_otp_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enquiry',
        ),
        migrations.AlterField(
            model_name='otp',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp_id',
            field=models.CharField(max_length=6),
        ),
    ]
