# Generated by Django 4.1.5 on 2023-04-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0020_delete_enquiry_alter_otp_address_alter_otp_otp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp_id',
            new_name='otp',
        ),
        migrations.RenameField(
            model_name='otp',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='otp',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
