# Generated by Django 4.1.5 on 2023-04-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0021_rename_otp_id_otp_otp_rename_phone_number_otp_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
