# Generated by Django 4.0.8 on 2023-04-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0022_rename_phone_otp_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='otp',
        ),
    ]
